import { Link } from 'react-router-dom'
import { ArrowLeft, FileText, ShieldCheck, Users } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Separator } from '@/components/ui/separator'

type LegalDocument = 'terms' | 'privacy' | 'community'

const DOCUMENTS: Record<LegalDocument, {
  title: string
  icon: typeof FileText
  intro: string
  sections: Array<{ heading: string; body: string }>
}> = {
  terms: {
    title: 'Yomy Terms of Service',
    icon: FileText,
    intro: 'These Terms explain the rules that apply when you use Yomy and the responsibilities you have as a member of the Yomy community.',
    sections: [
      {
        heading: '1. Using Yomy',
        body: 'You may use Yomy only in compliance with applicable laws and these Terms. You are responsible for keeping your account credentials secure and for activity performed through your account.',
      },
      {
        heading: '2. Your account',
        body: 'Provide information that is accurate and kept reasonably up to date. Do not impersonate another person, create deceptive accounts, or attempt to bypass security or access controls.',
      },
      {
        heading: '3. Content and conduct',
        body: 'You keep ownership of content you create, but you give Yomy the permissions needed to host, process, display, and deliver that content so the service can work. Do not use Yomy to distribute unlawful, abusive, threatening, fraudulent, or rights-infringing material.',
      },
      {
        heading: '4. Safety and enforcement',
        body: 'Yomy may restrict, remove, or suspend content or accounts when reasonably necessary to protect users, enforce these Terms, respond to legal obligations, or address abuse, fraud, or security threats.',
      },
      {
        heading: '5. Service changes',
        body: 'Yomy may add, change, or discontinue features as the service evolves. Where a change materially affects these Terms, we will provide an appropriate notice where required.',
      },
      {
        heading: '6. Contact and disputes',
        body: 'Questions about these Terms can be raised through Yomy support. Any mandatory rights or protections provided by the laws that apply to you remain unaffected by these Terms.',
      },
    ],
  },
  privacy: {
    title: 'Yomy Privacy Policy',
    icon: ShieldCheck,
    intro: 'This Policy describes, at a high level, what information Yomy may process, why it is used, and the choices available to you.',
    sections: [
      {
        heading: '1. Information you provide',
        body: 'Depending on the features you use, Yomy may process account information such as your name, username, email address, optional phone number, profile information, messages, media, and other content you choose to submit.',
      },
      {
        heading: '2. Information generated by the service',
        body: 'Yomy may process technical information such as device and app information, diagnostic data, security events, and usage information needed to operate, secure, and improve the service.',
      },
      {
        heading: '3. How information is used',
        body: 'Information may be used to provide account access, deliver messages and media, personalize the service, prevent abuse and fraud, maintain security, troubleshoot issues, and communicate important service information.',
      },
      {
        heading: '4. Phone number is optional',
        body: 'A phone number is not required to create an account in Yomy. If you choose to provide one, it may be processed for phone-related features such as verification or recovery when those features are enabled for your account.',
      },
      {
        heading: '5. Sharing and service providers',
        body: 'Yomy may rely on infrastructure and service providers that process information on its behalf, subject to appropriate contractual and technical safeguards. Yomy does not sell your personal information simply because you use the app.',
      },
      {
        heading: '6. Your choices',
        body: 'Depending on the feature and applicable law, you may be able to access, correct, download, or delete certain account information, or control privacy settings from within Yomy.',
      },
      {
        heading: '7. Policy updates',
        body: 'We may update this Policy as Yomy changes. The latest version and its effective date will be shown on this page.',
      },
    ],
  },
  community: {
    title: 'Yomy Community Guidelines',
    icon: Users,
    intro: 'Yomy is designed for people to communicate, share, and discover. These guidelines explain the behavior we expect across chats, profiles, stories, posts, and calls.',
    sections: [
      {
        heading: '1. Respect people',
        body: 'Do not harass, threaten, stalk, intimidate, or repeatedly target others. Respect boundaries and use blocking and reporting features when needed.',
      },
      {
        heading: '2. No harmful or illegal abuse',
        body: 'Do not use Yomy for unlawful activity, credible threats, fraud, malicious attacks, or content that puts people at serious risk of harm.',
      },
      {
        heading: '3. Authenticity matters',
        body: 'Do not impersonate people or organizations, manipulate identities to deceive others, or create coordinated deceptive activity intended to mislead users.',
      },
      {
        heading: '4. Protect privacy',
        body: 'Do not publish another person\'s private information without appropriate permission. Avoid sharing sensitive personal information in public spaces.',
      },
      {
        heading: '5. Respect intellectual property',
        body: 'Share content you have the right to use and do not intentionally infringe copyright, trademark, or other rights.',
      },
      {
        heading: '6. Enforcement',
        body: 'Yomy may limit visibility, remove content, restrict features, or suspend accounts when necessary to address serious or repeated violations or protect the community.',
      },
    ],
  },
}

export default function Legal({ document }: { document: LegalDocument }) {
  const data = DOCUMENTS[document]
  const Icon = data.icon

  return (
    <div className="min-h-screen bg-background px-4 py-6 sm:px-6">
      <div className="mx-auto w-full max-w-3xl space-y-5">
        <div className="flex items-center justify-between gap-3">
          <Link to="/signup" className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground">
            <ArrowLeft className="size-4" />
            Back to sign up
          </Link>
          <span className="text-[11px] text-muted-foreground">Version 2026-10-03</span>
        </div>

        <Card className="border shadow-sm">
          <CardHeader className="space-y-3">
            <div className="flex size-11 items-center justify-center rounded-2xl bg-primary/10 text-primary">
              <Icon className="size-5" />
            </div>
            <CardTitle className="text-2xl">{data.title}</CardTitle>
            <p className="text-sm leading-6 text-muted-foreground">{data.intro}</p>
            <p className="text-[11px] text-muted-foreground">Last updated: October 3, 2026</p>
          </CardHeader>
          <CardContent className="space-y-6">
            <Separator />
            {data.sections.map(section => (
              <section key={section.heading} className="space-y-2">
                <h2 className="text-sm font-semibold">{section.heading}</h2>
                <p className="text-sm leading-7 text-muted-foreground">{section.body}</p>
              </section>
            ))}
            <div className="rounded-2xl border bg-muted/30 p-4 text-xs leading-5 text-muted-foreground">
              This page is the current product-facing policy text for Yomy. Formal legal review should be completed before public launch in each jurisdiction where Yomy is offered.
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
